import type { CursorProject } from './types'

// Projects built/coded in Cursor. `featured: true` items surface as cards on
// the Work page; the rest exist only to populate the fake file-tree depth in
// the Home desktop Cursor window.
export const cursorProjects: CursorProject[] = [
  {
    id: 'overview',
    file: 'overview.md',
    group: 'frontdesk',
    name: 'Frontdesk',
    company: 'Birdeye · Lead Product Designer · 2024',
    tags: ['AI Agent', 'Healthcare'],
    description: 'An AI front desk agent for Birdeye\'s healthcare customers, covering scheduling, waitlists, pre-visit prep, and routing, designed and coded end to end.',
    outcome: 'Launched in 2 months. First deal $100K/3yrs. 4 agents, 3 tools, 50+ components built in code.',
    problem: 'Healthcare practices needed an AI front desk that could handle scheduling, waitlists, pre-visit prep, and routing, without losing patient trust.',
    process: {},
    detail: [
      'Designed 4 agents: Front Desk, Waitlist, Pre-Visit, Tagging & Routing',
      'Coded the component library (50+ components, 3 templates)',
      'Authored a Claude Skill that ships a full agent from a single prompt',
      'Adapted the existing builder for conversation building in 2 weeks',
    ],
    color: '#C9A86C',
    linkUrl: '#',
    linkLabel: 'View case study',
    featured: true,
  },
  {
    id: 'frontdesk-agent',
    file: 'frontdesk-agent.md',
    group: 'frontdesk',
    name: 'Frontdesk Agent',
    company: 'Birdeye · Myna · 2024',
    tags: ['AI Agent', 'Front Desk'],
    description: 'Handles inbound patient contact so a human isn\'t the first line of response.',
    outcome: 'One of 4 agents shipped as part of Myna, Birdeye\'s healthcare AI front desk.',
    detail: [
      'Handles inbound patient contact: scheduling, FAQs, and first-line triage before a human is looped in',
    ],
    color: '#C9A86C',
    linkUrl: '#',
  },
  {
    id: 'waitlist-agent',
    file: 'waitlist-agent.md',
    group: 'frontdesk',
    name: 'Waitlist Agent',
    company: 'Birdeye · Myna · 2024',
    tags: ['AI Agent', 'Waitlist'],
    description: 'Keeps open appointment slots filled without a staff member manually chasing the list.',
    outcome: 'One of 4 agents shipped as part of Myna, Birdeye\'s healthcare AI front desk.',
    detail: [
      'Manages waitlist entries and automated follow-up so open appointment slots get filled without manual chasing',
    ],
    color: '#C9A86C',
    linkUrl: '#',
  },
  {
    id: 'pre-visit-agent',
    file: 'pre-visit-agent.md',
    group: 'frontdesk',
    name: 'Pre-Visit Agent',
    company: 'Birdeye · Myna · 2024',
    tags: ['AI Agent', 'Pre-Visit'],
    description: 'Gets patients ready before they arrive, so the visit itself starts on time.',
    outcome: 'One of 4 agents shipped as part of Myna, Birdeye\'s healthcare AI front desk.',
    detail: [
      'Handles pre-visit prep: intake forms, reminders, and readiness checks ahead of an appointment',
    ],
    color: '#C9A86C',
    linkUrl: '#',
  },
  {
    id: 'tagging-routing-agent',
    file: 'tagging-routing-agent.md',
    group: 'inbox',
    name: 'Tagging & Routing Agent',
    company: 'Birdeye · Myna · 2024',
    tags: ['AI Agent', 'Routing'],
    description: 'Reads intent on the way in so every conversation lands with the right queue the first time.',
    outcome: 'One of 4 agents shipped as part of Myna, Birdeye\'s healthcare AI front desk.',
    detail: [
      'Tags incoming conversations by intent and routes them to the right queue or agent automatically',
    ],
    color: '#C9A86C',
    linkUrl: '#',
  },
  {
    id: 'query-fanout-agent',
    file: 'query-fanout-agent.md',
    group: 'search-ai',
    name: 'Query Fanout Agent',
    company: 'Birdeye · Search AI · 2024',
    tags: ['AI Agent', 'Search'],
    description: 'Answers a single query by pulling from multiple data sources at once instead of one at a time.',
    outcome: 'Part of Search AI, Birdeye\'s search agent work.',
    detail: [
      'Fans a single query out across multiple data sources in parallel and merges the results into one answer',
    ],
    color: '#5FB0C9',
    linkUrl: '#',
  },
  {
    id: 'domain-health-agent',
    file: 'domain-health-agent.md',
    group: 'search-ai',
    name: 'Domain Health Agent',
    company: 'Birdeye · Search AI · 2024',
    tags: ['AI Agent', 'Search'],
    description: 'Watches domain health signals so search issues get caught before they show up in results.',
    outcome: 'Part of Search AI, Birdeye\'s search agent work.',
    detail: [
      'Monitors domain health signals and surfaces issues before they affect search results',
    ],
    color: '#5FB0C9',
    linkUrl: '#',
  },
  {
    id: 'component-library',
    file: 'component-library.md',
    group: 'frontdesk',
    name: 'Agentic Builder Component Library',
    company: 'Birdeye · Myna · 2024',
    tags: ['Component Library'],
    description: 'The shared component library every agent-builder screen is built from, coded rather than handed off as specs.',
    outcome: '50+ components, 3 reusable templates, coded directly rather than handed off as specs.',
    detail: [
      'The shared component library every agent-builder screen is built from',
    ],
    color: '#C9A86C',
    linkUrl: '#',
  },
  {
    id: 'claude-skill',
    file: 'claude-skill.md',
    group: 'frontdesk',
    name: 'Agent-Building Claude Skill',
    company: 'Birdeye · Myna · 2024',
    tags: ['Claude Skill'],
    description: 'A Claude Skill that scaffolds a complete new agent, config UI included, from a single prompt.',
    outcome: 'Ships a full working agent, config UI included, from a single prompt.',
    detail: [
      'Authored the Claude Skill that scaffolds a complete new agent using the component library above',
    ],
    color: '#C9A86C',
    linkUrl: '#',
  },
  {
    id: 'rasoi',
    file: 'rasoi.md',
    group: 'exploratory',
    name: 'Rasoi',
    company: 'Personal project',
    tags: ['Self-Directed Build'],
    description: 'A cooking app project, built end to end outside of client work.',
    outcome: 'Self-directed build, designed and coded end to end.',
    detail: [
      'A cooking app project, built end to end outside of client work.',
    ],
    color: '#E8A23D',
    linkUrl: '#',
  },
  {
    id: 'araanya-registry',
    file: 'araanya-registry.md',
    group: 'exploratory',
    name: 'Araanya Birthday Registry',
    company: 'Personal project',
    tags: ['Self-Directed Build'],
    description: 'A birthday gift registry, built end to end outside of client work.',
    outcome: 'Self-directed build, designed and coded end to end.',
    detail: [
      'A birthday gift registry, built end to end outside of client work.',
    ],
    color: '#E8A23D',
    linkUrl: '#',
  },
]

export const cursorFolderGroups: { id: string; label: string }[] = [
  { id: 'frontdesk', label: 'frontdesk/' },
  { id: 'inbox', label: 'inbox/' },
  { id: 'search-ai', label: 'search-ai/' },
  { id: 'exploratory', label: 'exploratory/' },
]
