import type { CursorProject } from './types'

// Projects built/coded in Cursor. `featured: true` items surface as cards on
// the Work page; the rest exist only to populate the fake file-tree depth in
// the Home desktop Cursor window.
export const cursorProjects: CursorProject[] = [
  {
    id: 'myna',
    file: 'myna.md',
    group: 'frontdesk',
    name: 'Myna',
    company: 'Birdeye · Operations · 2026',
    tags: ['AI Agent', 'Healthcare', 'Operations'],
    description: "Birdeye had built its business on marketing products. As the industry shifted toward agentic AI, Birdeye made a structural bet: split the company's AI surface into three product lines by function rather than treating \"AI\" as a single feature: JAY for Marketing, Robin for CX, and Myna for Operations, an entirely new category for the company. Operations meant something concrete: businesses needed help with the unglamorous, high friction work of running a front desk: answering calls, booking and rescheduling appointments, verifying insurance, chasing down forms, filling cancelled slots. Birdeye sized the opportunity by vertical and prioritized healthcare first (the largest market), with dental and automotive queued behind it.",
    problem: "Before any of the three agents could be designed, the tool used to build them had a limit: Birdeye's agent builder was workflow based, meaning every agent was assembled as a linear, hardcoded flow. That approach doesn't scale past a handful of simple bots, and it couldn't support agents like Frontdesk that need to handle open ended intent, not a fixed script. I drove the shift from that agent builder to a conversational builder entirely on my own initiative, across two phases.",
    role: 'Lead Product Designer (Design Engineer)',
    team: '4 designers',
    timeline: '~2 months, 2026',
    detail: [
      "I led design for Myna's healthcare front desk and inbox domain, on a team of four designers shipping the first wave of Operations tools, agents, and reports in about two months. My own scope was the conversational builder transformation itself, plus three of the agents built on it: Frontdesk, Previsit, and Waitlist, covering the full patient journey from first contact through the visit itself. The rest of the team took care of the remaining agents and page level work across the product.",
      "This also landed in the middle of the team's shift away from designing in Figma toward designing in code, and the entire Myna healthcare project was handed over to engineering in code, not as Figma files.",
      "Phase 1 built out the conversational builder's core pieces: Settings (voice, chat, text), Triggers, Tools, Conversational nodes (Intent, greeting, transfer to agent, transfer to phone), and a Testing and Analysis experience spanning all three channels, so agents could be validated before going live.",
      "Phase 2 replaced Conversational nodes with Procedures, and the timing wasn't arbitrary: our voice backend, ElevenLabs, enabled Procedures as a platform capability right around then. Procedures simply weren't an option before that. The AgentArc team owned the Procedures concept itself, benchmarking how Sierra, Decagon, Intercom's Fin, Podium, and Voiceflow structure the same problem and settling on \"Procedures\" as the primary configurable unit over alternatives like \"Intents.\" From there, my team and I owned adapting our agents to it.",
      "With that foundation in place, I structured every agent around the same skeleton: Goals (a plain language statement of what the agent is responsible for), Outcomes (explicit, checkable success conditions, not just \"handle the call,\" but \"insurance is verified before the appointment is confirmed\" or \"no patient is left without a next step\"), Settings (channels, voice persona, language, per channel triggers), and Procedures (pulled from a shared library, each with its own tools attached). This was slower to design up front than writing a single flow for Frontdesk, but it paid off immediately once Previsit and Waitlist needed to reuse the same escalation and handoff logic instead of being built as separate, standalone bots.",
      "Frontdesk is the entry point: it takes inbound calls, texts, and web chats, identifies intent against the knowledge base, and manages the full appointment lifecycle (booking, rescheduling, cancelling, insurance verification) before escalating to a human with a full conversation summary when it can't resolve something itself. It runs under a dedicated voice persona, \"Veda Sky,\" a warm healthcare support tone, and identifies itself to callers by name.",
      "Previsit exists to get patients ready before they arrive, without adding to front desk workload. It triggers on every new booking, waits until seven days out, sends the intake form, checks completion two days later, and only escalates to an outbound voice call if the form is still incomplete, otherwise it ends quietly. Staff only hear about the patients who actually need a nudge.",
      "Waitlist turns cancellations into filled slots instead of lost revenue. When a slot opens, it waits 30 minutes before acting, then works through the waitlist via text and voice until the slot is filled or the list is exhausted. It doesn't carry an unfilled slot into the next day, and it respects do not disturb hours throughout.",
      "All three hand confirmed activity back to Frontdesk rather than operating as isolated bots, so a patient's history stays coherent no matter which agent touched it.",
      "Healthcare was the proving ground; dental and automotive are next behind it, using the same Goals/Outcomes/Procedures skeleton rather than starting over. The bigger unlock is that the architecture, not just the three agents, is now the reusable asset.",
      "I took that a step further and built a Claude Skill on top of the resulting component library that can ship an entire working agent from a single prompt, turning what used to be a multi week build into something that can spin up in minutes.",
    ],
    outcome: "The first healthcare customers signed on multiyear contracts, with one already expanding to a second location and another live across three locations from day one, early validation that Operations could stand alongside Marketing and CX as a real product line for Birdeye, not just a feature experiment.",
    color: '#C9A86C',
    linkUrl: '#',
    linkLabel: 'View case study',
    featured: true,
  },
  {
    id: 'frontdesk-agent',
    file: 'frontdesk-agent.md',
    group: 'frontdesk',
    name: 'Frontdesk Agent',
    company: 'Birdeye · Myna · 2024',
    tags: ['AI Agent', 'Front Desk'],
    description: "Frontdesk is the entry point for Myna's healthcare front desk: it takes inbound calls, texts, and web chats, identifies intent against the practice's knowledge base, and manages the full appointment lifecycle, booking, rescheduling, cancelling, insurance verification, before escalating to a human with a full conversation summary when it can't resolve something itself.",
    problem: "Practices needed a single agent that could stand in for the first line of front desk work across every channel, not a narrow scheduling bot, without losing the read on when a call actually needed a human.",
    outcome: "One of three agents I designed on Myna's conversational builder, covering the full patient journey from first contact through the visit itself.",
    detail: [
      'Runs under a dedicated voice persona, "Veda Sky," a warm healthcare support tone that identifies itself to callers by name rather than announcing itself as a bot.',
      "Built on the Goals / Outcomes / Settings / Procedures skeleton shared across Myna's agents, so escalation and handoff logic didn't need to be rebuilt per agent.",
      "Hands confirmed activity back to a shared patient record so Previsit and Waitlist stay in sync with whatever Frontdesk resolved.",
    ],
    color: '#C9A86C',
    linkUrl: '#',
  },
  {
    id: 'waitlist-agent',
    file: 'waitlist-agent.md',
    group: 'frontdesk',
    name: 'Waitlist Agent',
    company: 'Birdeye · Myna · 2024',
    tags: ['AI Agent', 'Waitlist'],
    description: "Waitlist turns cancellations into filled slots instead of lost revenue. When a slot opens, it waits 30 minutes before acting, then works through the practice's waitlist via text and voice until the slot is filled or the list is exhausted.",
    problem: "A cancelled appointment is lost revenue the moment front desk staff don't catch it fast enough, Myna needed to close that gap automatically, without spamming patients outside reasonable hours.",
    outcome: "One of three agents I designed on Myna's conversational builder, covering the full patient journey from first contact through the visit itself.",
    detail: [
      "Doesn't carry an unfilled slot into the next day, and respects do-not-disturb hours throughout the outreach.",
      "Hands confirmed bookings back to Frontdesk so a patient's history stays coherent regardless of which agent touched it.",
    ],
    color: '#C9A86C',
    linkUrl: '#',
  },
  {
    id: 'pre-visit-agent',
    file: 'pre-visit-agent.md',
    group: 'frontdesk',
    name: 'Pre-Visit Agent',
    company: 'Birdeye · Myna · 2024',
    tags: ['AI Agent', 'Pre-Visit'],
    description: "Previsit exists to get patients ready before they arrive, without adding to front desk workload. It triggers on every new booking, waits until seven days out, sends the intake form, checks completion two days later, and only escalates to an outbound voice call if the form is still incomplete.",
    problem: "Incomplete intake forms slow down the actual visit, but chasing every patient by hand doesn't scale, staff needed to hear only about the patients who actually needed a nudge.",
    outcome: "One of three agents I designed on Myna's conversational builder, covering the full patient journey from first contact through the visit itself.",
    detail: [
      'Ends quietly when a form is completed on time, so staff attention goes only to the patients who need a follow-up call.',
      'Shares the same escalation and handoff logic as Frontdesk and Waitlist rather than running as a standalone bot.',
    ],
    color: '#C9A86C',
    linkUrl: '#',
  },
  {
    id: 'tagging-routing-agent',
    file: 'tagging-routing-agent.md',
    group: 'inbox',
    name: 'Tagging & Routing Agent',
    company: 'Birdeye · Myna · 2024',
    tags: ['AI Agent', 'Routing'],
    description: 'Reads intent on the way in so every conversation lands with the right queue the first time.',
    outcome: 'One of 4 agents shipped as part of Myna, Birdeye\'s healthcare AI front desk.',
    detail: [
      'Tags incoming conversations by intent and routes them to the right queue or agent automatically',
    ],
    color: '#C9A86C',
    linkUrl: '#',
  },
  {
    id: 'query-fanout-agent',
    file: 'query-fanout-agent.md',
    group: 'search-ai',
    name: 'Query Fanout Agent',
    company: 'Birdeye · Search AI · 2024',
    tags: ['AI Agent', 'Search'],
    description: "The agent runs on demand: a user submits a prompt, the fanout estimator works out the related sub queries an AI engine would generate to answer it, and the agent turns that estimate into a final query list plus an output prompt, alerting the relevant people once the run completes. That output is surfaced to customers in a dashboard where they can trigger runs themselves and see the resulting fanout queries directly, rather than the fanout logic living only as an internal, invisible process.",
    problem: "Birdeye's Search AI, part of JAY (Marketing), already shows businesses how they rank on AI answer engines like ChatGPT, Claude, and Perplexity. But ranking data alone doesn't explain the full picture: when these engines answer a person's question, they quietly run a whole set of related sub queries behind the scenes, a process known as query fanout, before ever generating a single answer. Businesses had no way to see what those related queries actually were. Without that, there was no way to know what content to add to a business profile to show up across the full fanout, rather than just the one query someone typed in.",
    outcome: "This is still in development, not yet in front of customers, but it points at something bigger than one agent: a business's content strategy has traditionally been built around ranking for a handful of known keywords. Query fanout makes visible the much wider set of related questions an AI engine actually considers, which turns \"how do I rank\" into \"what do I need to say\" for an entire cluster of queries at once, not just one.",
    role: 'Lead Product Designer (solo design)',
    team: '1 designer, 1 PM, 1 EM',
    timeline: '1 week',
    status: 'In development',
    detail: [
      "I was the solo designer on this, working alongside a PM and an EM, and shipped it in a single week.",
    ],
    color: '#5FB0C9',
    linkUrl: '#',
  },
  {
    id: 'domain-health-agent',
    file: 'domain-health-agent.md',
    group: 'search-ai',
    name: 'Domain Health Agent',
    company: 'Birdeye · Search AI · 2024',
    tags: ['AI Agent', 'Search'],
    description: "The Domain Health Agent runs on a schedule. It fetches every domain listed for a business and loops through them one by one: checking whether the latest crawl for that domain has finished, then branching depending on the result. Once a domain's crawl is complete, the agent runs a full website health analysis, covering page facts, issues, scores, freshness, renderability, and recommendations. It then generates a report using an LLM and shares it on the Domain Health dashboard. If a crawl hasn't finished yet, the loop simply waits and checks again, rather than reporting on stale or incomplete data.",
    problem: "Showing up in an AI generated answer depends on more than having the right content: the AI engine has to be able to crawl and read a business's site in the first place. Broken pages, stale content, or pages that don't render properly all get in the way, quietly, without a business ever knowing that's why they're not being cited. Search AI needed a way to check the technical health of a business's domains on an ongoing basis, not just once.",
    outcome: "This is one of several agents inside Search AI looking at what makes a business visible to AI engines, and it covers the most foundational layer: whether the underlying site is even technically capable of being crawled and cited in the first place, regardless of how good the content on it is.",
    role: 'Lead Product Designer (solo design)',
    team: '1 designer, 1 PM, 1 EM',
    timeline: '1 week',
    status: 'In development',
    detail: [
      "I was the solo designer on this, working alongside a PM and an EM.",
    ],
    color: '#5FB0C9',
    linkUrl: '#',
  },
  {
    id: 'component-library',
    file: 'component-library.md',
    group: 'frontdesk',
    name: 'Agentic Builder Component Library',
    company: 'Birdeye · Myna · 2024',
    tags: ['Component Library'],
    description: "The shared component library every agent-builder screen in Myna is built from, coded directly in Cursor rather than handed off as Figma specs, so design and implementation stayed in lockstep through two phases of the builder's architecture.",
    problem: "Myna's conversational builder replaced a workflow-based tool with entirely new primitives (Settings, Triggers, Tools, Procedures), and each of the three agents needed those primitives to look and behave identically rather than drifting screen to screen.",
    outcome: '50+ components, 3 reusable templates, coded directly rather than handed off as specs.',
    detail: [
      'Covers the builder surfaces, nodes, procedures, testing and analysis, shared across Frontdesk, Previsit, and Waitlist.',
      'Became the foundation the Claude Skill below scaffolds new agents from.',
    ],
    color: '#C9A86C',
    linkUrl: '#',
  },
  {
    id: 'claude-skill',
    file: 'claude-skill.md',
    group: 'frontdesk',
    name: 'Agent-Building Claude Skill',
    company: 'Birdeye · Myna · 2024',
    tags: ['Claude Skill'],
    description: 'A Claude Skill that scaffolds a complete new agent, config UI included, from a single prompt, built on top of the Agentic Builder Component Library.',
    problem: "Once the component library and the Goals/Outcomes/Procedures skeleton existed, standing up a new agent was still a multi-week build. The pieces were reusable; the assembly still wasn't.",
    outcome: 'Ships a full working agent, config UI included, from a single prompt.',
    detail: [
      'Turns what used to be a multi-week build into something that can spin up in minutes, using the same components and skeleton as Frontdesk, Previsit, and Waitlist.',
      'Sets up dental and automotive, the next verticals behind healthcare, to reuse the architecture instead of starting over.',
    ],
    color: '#C9A86C',
    linkUrl: '#',
  },
  {
    id: 'rasoi',
    file: 'rasoi.md',
    group: 'exploratory',
    name: 'Rasoi',
    company: 'Personal project',
    tags: ['Self-Directed Build'],
    description: 'A cooking app project, built end to end outside of client work.',
    outcome: 'Self-directed build, designed and coded end to end.',
    detail: [
      'A cooking app project, built end to end outside of client work.',
    ],
    color: '#E8A23D',
    linkUrl: '#',
    hidden: true,
  },
  {
    id: 'araanya-registry',
    file: 'araanya-registry.md',
    group: 'exploratory',
    name: 'Araanya Birthday Registry',
    company: 'Personal project',
    tags: ['Self-Directed Build'],
    description: 'A birthday gift registry, built end to end outside of client work.',
    outcome: 'Self-directed build, designed and coded end to end.',
    detail: [
      'A birthday gift registry, built end to end outside of client work.',
    ],
    color: '#E8A23D',
    linkUrl: '#',
  },
]

export const cursorFolderGroups: { id: string; label: string }[] = [
  { id: 'frontdesk', label: 'frontdesk/' },
  { id: 'inbox', label: 'inbox/' },
  { id: 'search-ai', label: 'search-ai/' },
  { id: 'exploratory', label: 'exploratory/' },
]
